sonar.projectKey=Angular-Test
sonar.projectName=Angular Test
sonar.projectVersion=1.0

# Carpeta principal del código Angular
sonar.sources=src

# URL de tu servidor SonarQube
sonar.host.url=http://localhost:9000

# Token válido
sonar.token=squ_c57d68fff509ffafbcfa3cc42112e2101045ad95

