sonar.projectKey=parquimetros-test
sonar.projectName=parquimetros-test
sonar.projectVersion=1.0

# Carpeta principal del código Angular
sonar.sources=src

# URL de tu servidor SonarQube/SonarCloud
sonar.host.url=https://sonarcloud.io

# No incluyas tokens en el archivo. Pásalos por CI o -Dsonar.login


