sonar.projectKey=Prueba-Angular
sonar.projectName=Prueba de Angular
sonar.projectVersion=1.0
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.login=sqp_6e77f7ee6452a8a4fa9bd5928831ae62f33bf1b5

